### ISSUE TITLE
Windows.

### ISSUE THREAD

**Issue by xxl1212** [mibi88/Mibi_s_Tcl_Editor#3]
How to run IDE on Windows 10 ?

**Comment by mibi88** [comment]
* Compile or download a Tcl 8.6
* Add the file `tkcon.tcl` (https://sourceforge.net/projects/tkcon/files/tkcon/2.5/tkcon-2.5.tar.gz/download) next to the `index.tcl`.
* Check that tklib is installed.
* Run the `index.tcl` file : run this command : `path/to/wish8x.exe path/to/index.tcl`.

**Comment by mibi88** [comment]
With Tcl 8.5 it can works, with changes on the code (see picture).
![Capture d'écran 2021-06-13 12 39 05](https://user-images.githubusercontent.com/76903855/121804034-98e63c00-cc44-11eb-953c-ed838ebe6b25.png)

**Comment by xxl1212** [comment]
Thank you !
